name: Update README

on:
  push:
    paths-ignore:
    - 'README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Update README
      run: |
        rake readme
        git add README.md
        git commit -m "Updated README"
